const klarTargets = {
  abcnews: 7.036363636,
  wikiaFandom: 4.461818182,
  buzzfeed: 6.087272727,
  yelp: 5.836363636,
  eurosport: 8.236363636,
  ranker: 3.610909091,
  healthyway: 4.92,
  fashionbeans: 4.2,
  lifehacker: 12.36,
  spiegel: 11.52,
  nytimes: 16.08,
  reddit: 13.68,
  wired: 18.36,
  guardian: 10.08,
  medium: 3.72,
  washingtonpost: 9.84,
  cnbc: 12.72,
};

const graphDefaults = {
  api: 'android/klar',
  legend: ['focus (WV)', 'klar (GV)'],
  target: 'GV within 20% of WV',
  width: 600,
  height: 300,
  keys: ['focus', 'klar'],
  checkStatus: true,
  targetLine: 'klar',
};

const configuration = {
  abcnews: {
    ...graphDefaults,
    query: { site: 'abcnews.go.com' },
    title: 'abcnews.go.com',
    baselines: [{ value: klarTargets.abcnews, label: '+20%' }],
    targetValue: klarTargets.abcnews,
  },
  wikiaFandom: {
    ...graphDefaults,
    query: { site: 'wikia-fandom' },
    title: 'wikia/fandom',
    baselines: [{ value: klarTargets.wikiaFandom, label: '+20%' }],
    targetValue: klarTargets.wikiaFandom,
  },
  buzzfeed: {
    ...graphDefaults,
    query: { site: 'buzzfeed' },
    title: 'buzzfeed',
    baselines: [{ value: klarTargets.buzzfeed, label: '+20%' }],
    targetValue: klarTargets.buzzfeed,
  },
  yelp: {
    ...graphDefaults,
    query: { site: 'yelp.de' },
    title: 'yelp.de',
    baselines: [{ value: klarTargets.yelp, label: '+20%' }],
    targetValue: klarTargets.yelp,
  },
  eurosport: {
    ...graphDefaults,
    query: { site: 'eurosport.eu' },
    title: 'eurosport.eu',
    baselines: [{ value: klarTargets.eurosport, label: '+20%' }],
    targetValue: klarTargets.eurosport,
  },
  ranker: {
    ...graphDefaults,
    query: { site: 'm.ranker.com' },
    title: 'm.ranker.com',
    baselines: [{ value: klarTargets.ranker, label: '+20%' }],
    targetValue: klarTargets.ranker,
  },
  healthyway: {
    ...graphDefaults,
    query: { site: 'healthyway.com' },
    title: 'healthyway.com',
    baselines: [{ value: klarTargets.healthyway, label: '+20%' }],
    targetValue: klarTargets.healthyway,
  },
  fashionbeans: {
    ...graphDefaults,
    query: { site: 'fashionbeans.com' },
    title: 'fashionbeans.com',
    baselines: [{ value: klarTargets.fashionbeans, label: '+20%' }],
    targetValue: klarTargets.fashionbeans,
  },
  lifehacker: {
    ...graphDefaults,
    query: { site: 'lifehacker.com' },
    title: 'lifehacker.com',
    baselines: [{ value: klarTargets.lifehacker, label: '+20%' }],
    targetValue: klarTargets.lifehacker,
  },
  spiegel: {
    ...graphDefaults,
    query: { site: 'm.spiegel.de' },
    title: 'm.spiegel.de',
    baselines: [{ value: klarTargets.spiegel, label: '+20%' }],
    targetValue: klarTargets.spiegel,
  },
  nytimes: {
    ...graphDefaults,
    query: { site: 'nytimes.com' },
    title: 'nytimes.com',
    baselines: [{ value: klarTargets.nytimes, label: '+20%' }],
    targetValue: klarTargets.nytimes,
  },
  reddit: {
    ...graphDefaults,
    query: { site: 'reddit.com' },
    title: 'reddit.com',
    baselines: [{ value: klarTargets.reddit, label: '+20%' }],
    targetValue: klarTargets.reddit,
  },
  wired: {
    ...graphDefaults,
    query: { site: 'wired.com' },
    title: 'wired.com',
    baselines: [{ value: klarTargets.wired, label: '+20%' }],
    targetValue: klarTargets.wired,
  },
  guardian: {
    ...graphDefaults,
    query: { site: 'guardian.co.uk' },
    title: 'guardian.co.uk',
    baselines: [{ value: klarTargets.guardian, label: '+20%' }],
    targetValue: klarTargets.guardian,
  },
  medium: {
    ...graphDefaults,
    query: { site: 'medium.com' },
    title: 'medium.com',
    baselines: [{ value: klarTargets.medium, label: '+20%' }],
    targetValue: klarTargets.medium,
  },
  washingtonpost: {
    ...graphDefaults,
    query: { site: 'washingtonpost.com' },
    title: 'washingtonpost.com',
    baselines: [{ value: klarTargets.washingtonpost, label: '+20%' }],
    targetValue: klarTargets.washingtonpost,
  },
  cnbc: {
    ...graphDefaults,
    query: { site: 'cnbc.com' },
    title: 'cnbc.com',
    baselines: [{ value: klarTargets.cnbc, label: '+20%' }],
    targetValue: klarTargets.cnbc,
  },
};

export default configuration;
